# -*- coding: utf-8 -*-
"""코로나-메르스 소비 패턴.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bR01QQXL83wPUHk3Vap6H8RXj9GWHY2X

# 삼성카드 메르스_코로나 소비 유형 분류
"""

import pandas as pd
import numpy as np
import csv

path = '/content/drive/MyDrive/ML Deep/코로나 분석/'
name = 'DATA_SSC_CORONA_MERS.csv'

df = pd.DataFrame(pd.read_csv(path + name))
df.head()

# 연도별 정리하기 
# date_info = df.소비일자.values
type(date_info[1])

date_infomation = [str(row) for row in date_info]
type(date_infomation[5])
df['소비일자'] = date_infomation

df['연도'] = df['소비일자'].str[0:4]
df['월별'] = df['소비일자'].str[5]

df = df.drop(['소비일자'], axis=1)
consum_list = set(df['소비업종'])
consum_list

# groupby 로 원하는 변수를 조건으로 주어 추출
# 월별 소비는 의미가 없음으로 두고 합친다
data_group = df.groupby([df['소비업종'],df['성별'],df['연령대'],df['연도']], as_index=False).sum()

# 파생변수 추가 
# 업종별 소비건수 합계 차이
a = data_group[data_group['소비업종']=='가전/가구']
b = data_group[data_group['소비업종']=='가정생활/서비스']
c = data_group[data_group['소비업종']=='교육/학원']
e = data_group[data_group['소비업종']=='미용']
f = data_group[data_group['소비업종']=='백화점/상품권/아울렛']
g = data_group[data_group['소비업종']=='스포츠/문화/레저']
h = data_group[data_group['소비업종']=='여행/교통']
i = data_group[data_group['소비업종']=='요식/유흥']
j = data_group[data_group['소비업종']=='의료']
k = data_group[data_group['소비업종']=='자동차']
l = data_group[data_group['소비업종']=='주유']
n = data_group[data_group['소비업종']=='패션/잡화']
m = data_group[data_group['소비업종']=='편의점']
o = data_group[data_group['소비업종']=='할인점/마트']

# 그룹화된 막대 그래프 그리기
class group_bar(self):
  
  def group(self, data):
    
      width = 0.4
      left_x = []
      middle_x = []
      right_x = []
      for position in data.values:
        if position[3] == '2015':
          left_x.append(position[4])
        elif position[3] == '2019':
          middle_x.append(position[4])
        else:
          right_x.append(position[4])
      x = [1,2,3,4,5]
      le = []
      mi = []
      ri =[]
      for row in x:
        le.append(row-width/2)
        mi.append(row)
        ri.append(row+width/2)

  def bar(self,x_name, y_name):
    # 연령대
    age_category = sorted(set(data['연령대']))
    plt.rcParams['font.family']= 'NanumGothic'
    plt.bar(self.le,self.left_x, color='r' ,width=width,label='2015')
    plt.bar(self.mi,self.middle_x,color='g',width=width,label='2019')
    plt.bar(self.ri,self.right_x,color='b',width=width,label='2020')
    plt.legend(loc='up right',ncol=1)
    plt.xticks(self.mi, age_category, fontsize=14, rotation=0)
    plt.xlabel(x_name)
    plt.ylabel(y_name)
    plt.show()
